2020-05-13 11:09:47,355 INFO: Microblog startup [in /home/x-man/Programming/Flask-microblog/app/__init__.py:47]
2020-05-13 11:12:26,502 INFO: Microblog startup [in /home/x-man/Programming/Flask-microblog/app/__init__.py:47]
2020-05-13 11:12:33,293 ERROR: Exception on /edit_profile [POST] [in /home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/x-man/Programming/Flask-microblog/app/routes.py", line 91, in edit_profile
    db.session.commit()
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 995, in _emit_update_statements
    statement, multiparams
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/x-man/Programming/Flask-microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('susan', 'Hi', 2)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2020-05-13 11:18:07,118 INFO: Microblog startup [in /home/x-man/Programming/Flask-microblog/app/__init__.py:47]
2020-05-13 11:42:11,171 INFO: Microblog startup [in /home/x-man/Programming/Flask-microblog/app/__init__.py:47]
2020-05-13 11:43:15,648 INFO: Microblog startup [in /home/x-man/Programming/Flask-microblog/app/__init__.py:47]
2020-05-13 12:18:50,903 INFO: Microblog startup [in /home/x-man/Programming/Flask-microblog/app/__init__.py:47]
2020-05-13 12:23:34,368 INFO: Microblog startup [in /home/x-man/Programming/Flask-microblog/app/__init__.py:47]
2020-05-13 14:41:58,316 INFO: Microblog startup [in /home/x-man/Programming/Flask-microblog/app/__init__.py:47]
2020-05-13 15:29:23,568 INFO: Microblog startup [in /home/x-man/Programming/Flask-microblog/app/__init__.py:47]
2020-05-13 15:40:33,037 INFO: Microblog startup [in /home/x-man/Programming/Flask-microblog/app/__init__.py:47]
2020-05-14 12:36:07,370 INFO: Microblog startup [in /home/x-man/Programming/Flask-microblog/app/__init__.py:49]
2020-05-14 13:23:00,712 INFO: Microblog startup [in /home/x-man/Programming/Flask-microblog/app/__init__.py:49]
2020-05-14 16:43:30,803 INFO: Microblog startup [in /home/x-man/Programming/Flask-microblog/app/__init__.py:51]
2020-05-14 16:55:36,762 INFO: Microblog startup [in /home/x-man/Programming/Flask-microblog/app/__init__.py:51]
2020-05-14 17:33:12,798 INFO: Microblog startup [in /home/x-man/Programming/Flask-microblog/app/__init__.py:56]
